#################################################
# Makefile for JPEG_V2 
# 2009 (C) Samsung Electronics 
# Author : Jaeryul peter Oh <jaeryul.oh@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_JPEG_V2)	+= jpg_mem.o jpg_misc.o jpg_opr.o s3c-jpeg.o

EXTRA_CFLAGS += -Idrivers/media/video

