obj-$(CONFIG_PHONE_ARIES)	+= modemctl/
obj-$(CONFIG_PHONE_ARIES)	+= onedram/
obj-$(CONFIG_PHONE_ARIES)	+= svnet/
#obj-$(CONFIG_PHONE_ARIES_CDMA)	+= modemctl_cdma/
obj-$(CONFIG_PHONE_ARIES_CDMA)	+= onedram_cdma/
#obj-$(CONFIG_PHONE_ARIES_CDMA)	+= svnet_cdma/
obj-$(CONFIG_PHONE_CRESPO)	+= modem_ctl.o modem_io.o modem_dbg.o
